### ISSUE TITLE
Error in Chrome C# Connection

### ISSUE THREAD

**Issue by Su-s** [BrettHewitt/dataDyneChromeServerHost#1]
Hi

I had configured I got error that this error 

An unhandled exception of type 'native_messaging_app.NotRegisteredWithChromeException' occurred in native_messaging_app.dll

that app has not registerd

**Comment by BrettHewitt** [comment]
Hi Su-s, the manifest file required for this to work must be added to your registry, otherwise you get that error. The installer (https://datadyne.bretthewitt.net/datadynechromeextension.php) will automatically do this for you, but if you're trying to run it directly from source you will need to do some configuration. https://developer.chrome.com/apps/nativeMessaging provides information on everything that's needed.

![image](https://user-images.githubusercontent.com/7501871/74605751-ba6ffb80-50c2-11ea-9fab-cb9207b6003e.png)

Brett

**Comment by Su-s** [comment]
thanks for the reply @BrettHewitt 

![image](https://user-images.githubusercontent.com/37269911/74606021-fe7af480-50f2-11ea-94b7-a3fb91fb39a8.png)


i had added the manifest file path 


```
{
  "key": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjWGe656qa6bKMRCE7Miha2e32msA74Qu4DOz12TXUyxqjPTrkwbD5YMUilT5wDfDGpXyfPlP+LqAADiqn0R/qOAcr1Uek93iWT4zgeDGT/ny0OxiGMRpZ5DslL9U5vuluV2EVRWzcZREoVrYbX3TxvXGjOEQZ+rawIHPzrcQcLeh4DEoh8r4xST3mnM/6LUYO2Y/k6vmerxS6OIu9UgN8uz6NmD5t8K3kHLyxuxAse6ltWre80eQdN0Gk6mqZn5gSUK0/PBPgOlqVni7lhrDZt+qsr1aBOyCKfLhA7pe/x3SwfK54dTdlaOa/tObUvb3qDA5Q0ayb1oGPnxDDqWxCQIDAQAB",
  "name": "dataDyne Laboratories Communication Server",
  "version": "1.3.4",
  "manifest_version": 2,
  "description": "dataDyne Communication Extension to interact with the Service Host",
  "background": {
    "scripts": ["main.js"],
    "persistent": true
  },
  "icons": {
    "128": "icon-128.png"
  },
  "permissions": [
    "nativeMessaging",
	"tabs"
  ]
}

```

these are the contents of manifest file that i have

**Comment by BrettHewitt** [comment]
Hi Su-s, the manifest file must be in the same location as your executable. Also, that's the manifest file for the chrome extension, rather than the native messaging. For example, my native messaging manfiest file looks like `{"name":"com.datadyne.chromeserver.message","description":"dataDyne Chrome Messaging Server","path":"C:\\Program Files\\dataDyneChromeCommunicationServer\\dataDyneChromeServerHost.exe","type":"stdio","allowed_origins":["chrome-extension://pdfpdlimkepkmdpopmccbjdpiagnegne/"]}`

**Comment by Su-s** [comment]
thankyou @BrettHewitt i will configure it

**Comment by Su-s** [comment]
but @BrettHewitt  i have another doubt that we have to set the path for the application 
`"path":"C:\\Program Files\\dataDyneChromeCommunicationServer\\dataDyneChromeServerHost.exe"`
like this
so is it necessary to maintain the exe and manifest in same file?

**Comment by BrettHewitt** [comment]
It is still necessary to place the manifest and exe in the same folder. Change `"path":"C:\\Program Files\\dataDyneChromeCommunicationServer\\dataDyneChromeServerHost.exe"` to the location of your executable. Once you do that it should start ok and you should be able to communicate with Chrome, provided you have the dataDyne Chrome Extension installed.

**Comment by Su-s** [comment]
ok thankyou @BrettHewitt

**Comment by Su-s** [comment]
![image](https://user-images.githubusercontent.com/37269911/74606493-d68d9000-50f6-11ea-8284-5174a24a826d.png)

I had added the files as you said and the console application is working but the error in chrome extension is still existing.

![image](https://user-images.githubusercontent.com/37269911/74606519-1785a480-50f7-11ea-8c6f-2f16b9f51894.png)

**Comment by BrettHewitt** [comment]
Are you using the dataDyne Extension or your own custom extension? Also, if you start Chrome from the command line with the following flag `--enable-logging` it should give more detailed information.

**Comment by Su-s** [comment]
Thanks for the support. I cloned your repo and using the same. I am new to chrome app development and IPC so I am using your extension to learn how it works.

I had started the c# application and got a  blank screen 

and in Chrome app there is an error

![image](https://user-images.githubusercontent.com/37269911/74606912-5ff29180-50fa-11ea-9f35-1adc3cd3a8b4.png)

**Comment by BrettHewitt** [comment]
You shouldn't start the dataDyneChromeServerHost from Visual Studio, the Chrome Extension will start up in headless mode so the console won't be visible. You can then attach to the Native Messaging process via visual studio if you wish to debug it.

Did you run Chrome from the command line with the `--enable-logging` flag? Please can you post the output from the command line

**Comment by Su-s** [comment]
yes i had ran chrome from command line 

![image](https://user-images.githubusercontent.com/37269911/74607122-e9569380-50fb-11ea-904f-d09ee2d218f6.png)

and this is the output the menu item communication server is disabled

**Comment by Su-s** [comment]
> You can then attach to the Native Messaging process via visual studio if you wish to debug it.

Can you please explain how can we do that, because for me the dataDyne communication server is disabled

**Comment by BrettHewitt** [comment]
I was hoping the command line would provide something more useful! I'm not sure why it is quitting if the code hasn't been modified without looking at the error myself. The only other thing I could recommend is rebuild the project with `System.Diagnostics.Debugger.Launch();` added to Program.cs and as the first line to be executed in the Main(string[] args) method. Then attach visual studio to it when Chrome tries to load the extension, and see what error comes up in Visual Studio

**Comment by Su-s** [comment]
Unfortunately, I didn't found any statement `System.Diagnostics.Debugger.Launch();` in the code I had searched the entire code

**Comment by BrettHewitt** [comment]
What you've done is correct. Now if you close Chrome and reopen it, you should get a popup when the program starts which will let you select Visual Studio to debug it. If you don't get the popup, then there's a problem with your configuration as it's not trying to start the program.

**Comment by Su-s** [comment]
hi this is the output from visual studio

![image](https://user-images.githubusercontent.com/37269911/74607867-6c7ae800-5102-11ea-8cb4-dd602827ecbe.png)


![image](https://user-images.githubusercontent.com/37269911/74607872-7c92c780-5102-11ea-9cba-4f84d7e7dfe5.png)

**Comment by BrettHewitt** [comment]
Everything looks fine there, if you keep stepping through the code you should be able to find the location where the application throws an exception/quits

**Comment by Su-s** [comment]
exited right here    stdin.Read(lengthBytes, 0, 4);
in hosts.cs

**Comment by BrettHewitt** [comment]
What was the exception? Once it gets to that part it should just wait until a command comes in

**Comment by Su-s** [comment]
but how can we send message from chrome

**Comment by BrettHewitt** [comment]
This extension won't receive a message from Chrome on its own, it needs a message to be sent externally first before it responds. A better example for you to work might be https://github.com/anewtonlevey/NativeMessaging 

That's the example I used to learn about it all

**Comment by Su-s** [comment]
Thanks for the tutorial. I will surely go through this. So how can we send messages externally? means I didn't get the idea of how the command comes in or how we input the command to make this communicating

**Comment by Su-s** [comment]
I will refer this code Thankyou @BrettHewitt for the support
